### ISSUE TITLE
MidiBus Warning: Disabling controllerChange

### ISSUE THREAD

**Issue by dandaka** [DerekCook/CoreMidi4J#11]
My Processing script stops working with CoreMIDI4J error.

```
The MidiBus Warning: Disabling controllerChange(int channel, int number, int value) because an unkown exception was thrown and caught
java.lang.reflect.InvocationTargetException
  at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at themidibus.MidiBus.notifyParent(Unknown Source)
  at themidibus.MidiBus$MReceiver.send(Unknown Source)
  at uk.co.xfactorylibrarians.coremidi4j.CoreMidiSource.transmitMessage(CoreMidiSource.java:727)
  at uk.co.xfactorylibrarians.coremidi4j.CoreMidiSource.messageCallback(CoreMidiSource.java:470)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 123
  at hype_midi.controllerChange(hype_midi.java:67)
  ... 7 more
Finished.
[Finished in 276.8s]
```

Code is here, pretty simple.
https://github.com/deepower/p-visuals/blob/master/hype_midi/hype_midi.pde

I use Processing script as a MIDI client and Ableton Live as a server. I launch Live without Processing. Then I start Live, Processing gets MIDI messages. When I stop Live, Processing crashes.

**Comment by brunchboy** [comment]
From my quick scan of that exception, it is not occurring in CoreMIDI4J, but in your own MIDI event handler. I suspect you are getting a `number` value that is > 8, so `knobValues[number]` is causing your `ArrayIndexOutOfBoundsException`. In fact looking again, `number` appears to be `123`, which would definitely do that.

**Comment by dandaka** [comment]
God bless you, James! :clap:

**Comment by brunchboy** [comment]
I’m glad I could help. Java stack traces can be harder to decipher than they should be. :smile:
